version: "3"
services:

  web_frontend:
    image: micro_frontend
    command: npm run start
    build: ./microservices/web_service/client
    ports:
      - 3000:3000
    networks:
      - webnet


  authentication_service:
    image: authentication_service
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    build: ./microservices/authentication_service
    ports:
      - "3001:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_DB_URI=mongodb://mongodb/micro_users
    networks:
      - webnet

  group_service:
    image: group_service
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    build: ./microservices/group_service
    ports:
      - "3002:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_DB_URI=mongodb://mongodb/micro_groups
    networks:
      - webnet

  message_service:
    image: message_service
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    build: ./microservices/message_service
    ports:
      - "3003:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_DB_URI=mongodb://mongodb/micro_messages
    networks:
      - webnet

  mongodb:
    image: mongo
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "27017:27017"
    networks:
      - webnet


networks:
  webnet:
